name: realtime_stocks
version: 1.0.0
profile: rtsa_athena

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analyses"]
test-paths: ["tests"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

seeds:
  realtime_stocks:
    +schema: rtsa_ref # Athena schema for reference/lookup tables
    +quote_columns: false
    +column_types:
      SYMBOL_V: varchar
      GROUP_ID: varchar
      GROUP_NAME: varchar
