version: 2

models:
  - name: silver_ticks
    description: "Clean view from ticks_raw_parquet with readable timestamp"
    columns:
      - name: ts
        description: "Event time in epoch ms"
        tests:
          - not_null
      - name: price
        description: "Last traded price"
        tests:
          - not_null
